---
title: "The Quantified Self"
header-includes: \usepackage{caption}
output: pdf_document
fig_caption: no
---

```{r Settings, echo = FALSE, eval = TRUE, results = "hide", warning = FALSE, message = FALSE}
rm(list=ls())

# List loaded packages
# (.packages())

# Packages loaded
pck_loaded <- (.packages())

# Packages to load
pck_toload <- c('ggplot2', 'mvtnorm', 'data.table', 'sqldf', 'stargazer', 'xtable')

# Load packages
for(i in 1:length(pck_toload)) {
   if (!pck_toload[i] %in% pck_loaded)
    print(pck_toload[i])
    library(pck_toload[i], character.only = TRUE)
}

```

\captionsetup[table]{labelformat=empty}

### Getting the data
```{r Data_1, echo = TRUE, eval = TRUE, results = "show", warning = FALSE, message = FALSE}

# Load the data
setwd("C:/repos_github/coursera/repres/data")
dt1 <- read.table("activity.csv", sep = ",", header = TRUE)
dt1 <- data.table(dt1)
names(dt1)
length(names(dt1))

# Remove missing values
dt2 <- dt1[complete.cases(dt1),]

# Rows with missing data removed
naRemoved <- nrow(dt1) - nrow(dt2)
dt1 <- dt2
remove(dt2)
```

### Analysis part 1 - The data table way
```{r Analysis_1, echo = TRUE, eval = TRUE, results = "show", warning = FALSE, message = FALSE, fig.width = 12, fig.height = 8}

# Number of steps per day, data.table
dt2 <- dt1[,.(steps.sum = sum(steps)),by=date]

# Number of steps per day, sqldf
dt2s <- sqldf("SELECT sum(steps), date 
        FROM dt1
        Group by date")

names(dt2)

# Number of steps per day, calculations
nsteps <- sum(dt2$steps)
avgsteps <- mean(dt2$steps.sum)
medsteps <- median(dt2$steps.sum)


# Histogram of number of steps per day
h1 <- ggplot(data=dt2, aes(dt2$steps.sum), xlab = "steps") + geom_histogram()
h1 <- h1 + theme_classic()
h1 <- h1 + ggtitle("Number of steps") + xlab("steps")
plot(h1)

```


\captionsetup[table]{labelformat=empty}

